AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    # The gemspec file is an exception, it breaks all the rules
    - '*.gemspec'
# you've already upped this. twice.
Metrics/LineLength:
  Max: 160
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
