version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-browsers
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - run:
          name: Rubocop lint
          command: bundle exec rubocop -D
      - run:
          name: Rspec tests
          command: bundle exec rspec --color --require spec_helper --format NyanCatFormatter spec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
